version: "3"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nba
    container_name: nba-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default
#  mysql:
#    image: mysql:latest
#    container_name: nba-db-mysql
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#    networks:
#      - default
  pgsql:
    image: postgres:latest
    container_name: nba-db-pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    networks:
      - default
  nginx:
    image: nginx:latest
    container_name: nba-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - default

networks:
  default:
    driver: bridge